services:
  db:
    image: postgres:13-alpine
    container_name: todo-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    container_name: todo-api
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/todo
      JWT_SECRET_KEY: your-secret-key

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    container_name: todo-web
    ports:
      - "3001:3001"
    depends_on:
      - api

volumes:
  postgres_data:
