services:
  db:
    image: postgres:13-alpine
    container_name: todo-db
    environment:
      POSTGRES_DB: todo_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    container_name: todo-api
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:postgres123@db:5432/todo_db
      JWT_SECRET_KEY: your-super-secret-jwt-key-change-in-production

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    container_name: todo-web
    ports:
      - "3001:3001"
    depends_on:
      - api
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3000

volumes:
  postgres_data:
