name: CI API

on:
  push:
    branches: [main]

  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Generate Prisma Client
        run: pnpm prisma generate
        working-directory: ./apps/api

      - name: Build
        run: pnpm build
        working-directory: ./apps/api

      - name: Lint
        run: pnpm lint
        working-directory: ./apps/api

      - name: Test
        run: pnpm test
        working-directory: ./apps/api
